
#DropDB VISA2014EasyTest
#Application VISA2014.Win

*Action New
*FillForm
*ExecuteEditorAction Region
*Action New
*FillForm
 Name Of Region = Daşoguz welaýaty
 Name Of Region L = Daşoguz welaýaty
*Action Save and Close
*ExecuteEditorAction City
*Action New
*FillForm
 Name Of City = Görogly etraby
 Name Of City L = Görogly etraby
*Action Save and Close
*FillForm
 Address Line = Daýanç 45
*ExecuteEditorAction Document Of Address
*Action New
*FillForm
 Type Of Document = Patent
*Action Save and Close
*FillForm
 Expiring Date Of Address Document = 2/11/2013
*Action Save
*Action Save and Close
