
*Action Navigation(Application.SimpleProcessApplication)
*ProcessRecord 
 Registration Number = 4/-7
*Action Application Result
*Action Application Result.New
*Action Application Result
*FillForm
 Result = Invitation
 Number = ASGH-1487
 Issued Date = 18.01.2013
 Date Of Expire = 18.03.2013
 Visa Category = Köp gezeklik
 Visa Period = 6 aý
*Action Person In Result Letter
*Action Person In Result Letter.New
*FillForm
 Family Member = Jeren Meredowa
 Expected Date Of Arrival = 18.01.2013
*Action Save and Close
*Action Save and Close
*Action Save and Close
