
*Action Navigation(FamilyMember.FamilyMember)
*ProcessRecord 
 Full Name = Jeren Meredowa
*Action Passports
*ProcessRecord Passports
 Passport Number = NEWFM000001
*Action Visas.New
*FillForm
 ASNumber = AS-145878
 Visa Number = NVFM000001
 Visa Type = BS
 Visa Category = Köp gezeklik
 Visa Issued Place = Aşgabat şäher howa menzilindäki MGP
 Visa Issued Date = 18.05.2013
 Visa Start Date = 18.05.2013
 Visa End Date = 18.07.2013
*Action Save and Close
*Action Save and Close
*Action Save
