
*Action Navigation(Application.LongProcessApplication)
*ProcessRecord 
 Registration Number = 120
*Action IApplication
*Action Application Result
*Action Application Result.New
*Action Application Result
*FillForm
 Number = ASGH1
 Issued Date = 10.01.2013
 Visa Category = Köp gezeklik
 Visa Period = 6 aý
 Date Of Expire = 10.03.2013
*Action Person In Result Letter
*Action Person In Result Letter.New
*FillForm
 Employee = Serdar Aşyrow
 Expected Date Of Arrival = 15.03.2013
;Save and close Person In Result
*Action Save and Close
;Save and Close App result
*Action Save and Close
