
*Action Navigation(Application.SimpleProcessApplication)
*Action New(Simple Process Application)
*Action IApplication
*FillForm
 For Employee = True
 Base Application Type = Invitation
 Application Type For Employee = Application for changing invitation
 Auto Registration = False
 Manual Application Number = 121
 Manual Application Date = 20.01.2013
 Invitation To Be Changed = ASGH1
*Action LayoutTab.Person In Application
*Action Person In Application.New
*Action IPerson In Application
*FillForm
 Employee = Serdar Aşyrow
 Address = Çandybil etraby;Address Of Janet Levering
*CheckFieldValues
 Passport = 20202020
*Action Save and Close
*Action Save and Close
