*Action Visas
*Action Visas.New
*Action IVisa
*FillForm
 ASNumber = AS-004
 Visa Number = A04
 Visa Type = BS
 Visa Category = Köp gezeklik
 Visa Issued Place = Aşgabat şäher howa menzilindäki MGP
 Visa Issued Date = 01.11.2014
 Visa Start Date = 01.11.2014
 Visa End Date = 01.05.2015
 Has Border Zone Permit = True
*ExecuteEditorAction Border Zone
*Action New
*FillForm
 Daşoguz = True
 Tagtabazar = True
;Save and Close BorderZone
*Action Save and Close
;Save and close Visa
*Action Save and Close