*Action Visas
*Action Visas.New
*Action IVisa
*FillForm
 ASNumber = AS-001
 Visa Number = A01
 Visa Type = BS
 Visa Category = Köp gezeklik
 Visa Issued Place = Aşgabat şäher howa menzilindäki MGP
 Visa Issued Date = 01.05.2013
 Visa Start Date = 01.05.2013
 Visa End Date = 01.11.2013
 Has Border Zone Permit = True
*ExecuteEditorAction Border Zone
*Action New
*FillForm
 Daşoguz = True
 Tagtabazar = True
;Save and Close BorderZone
*Action Save and Close
;Save and Close Visa
*Action Save and Close

