*Action Visas
*Action Visas.New
*Action IVisa
*FillForm
 Visa Number = 2154877
 Visa Type = BS
 Visa Category = Köp gezeklik
 Visa Issued Place = Aşgabat şäher howa menzilindäki MGP
 Visa Issued Date = 15.01.2013
 Visa Start Date = 15.01.2013
 Visa End Date = 15.04.2013
 ASNumber = 0001
 Has Border Zone Permit = True
*ExecuteEditorAction Border Zone
*Action New
*FillForm
 Daşoguz = True
 Tagtabazar = True
;Border Zone
*Action Save and Close
;Visa
*Action Save and Close
