*Action Navigation(Work Permit.Work Permit Letter)
*Action New(Work Permit Letter)
*Action Work Permit Letter
*FillForm
 Number = 0146
 Date = 01.01.2013
*Action Work Permits
*Action Work Permits.New
*FillForm
 ASNumber = AS-001
 Employee = Serdar Aşyrow
*ExecuteEditorAction Work Permit Location
*Action New
*Action Daşoguz welaýaty
*FillForm
 Daşoguz Şäheri = True
*Action Ahal welaýaty
*FillForm
 Tejen Şäheri = True
*Action Save and Close
*FillForm
 Start Date Of Work Permit = 01.01.2013
 Expiring Date Of Work Permit = 01.04.2013
 Appruval Number = 0146/1
*Action Save and Close
*Action Save and Close

